FROM node:latest

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the app directory
COPY package*.json ./

# Install app dependencies as root
RUN npm install
RUN npm install cors
RUN npm install express
RUN npm install mongodb

# Switch to a non-root user if needed
# USER node

# Copy your application code to the container
COPY . .

# Expose the port your app will run on
EXPOSE 3005

# Define the command to run your app
CMD ["node", "stories.js"]
